paths:
  db: .clasi/.clasi.db
  design: docs/design
  issues: clasi/issues
  logs: .clasi/log
  reflections: clasi/reflections
  sprints: clasi/sprints
process: se
design_docs: enabled
sources:
- src/clasi
protected_paths:
- src
- tests
excluded_paths:
- tests/e2e
